### ISSUE TITLE
Revisit ToString implementation for response classes

### ISSUE THREAD

**Issue by pgautier404** [momentohq/client-sdk-dotnet#314]
Currently the response classes that hold a value emit that value as part of their `ToString()` override, but those values can be unsuitable for representation in that way (e.g., super long, binary, etc.). We need to settle on a sensible way to represent this value information.

**Comment by malandis** [comment]
1. The data has one representation (bytes) and we can marshal to strings.
2. If the byte array actually represents pure binary data and not a human-readable string, a UTF-8 conversion will render a mess of non-printing characters. Because of we do not know which an end-user would prefer a priori, we should print both bytes and string representation.
4. .NET has a class to pretty print byte arrays as hex. See [here](https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.tostring?view=net-6.0#system-bitconverter-tostring(system-byte()))

Example:

```csharp
using System;

public class Printer
{
    public byte[] ValueByteArray { get; set; }
    public string ValueString { get => Encoding.UTF8.GetString(ValueByteArray); }
    public Printer(byte[] valueByteArray)
    {
        this.ValueByteArray = valueByteArray;
    }

    public override string ToString()
    {
        return $"{base.ToString()}: ValueByteArray: {BitConverter.ToString(ValueByteArray)} - ValueString: {ValueString}";
    }
}

// later
var val = new PrintIt(new byte[] { 0x00, 0x01, 0xAF  });
Console.WriteLine(val);
// ...Printer: ValueByteArray: 00-01-AF - ValueString: �
 
val = new Printer(Encoding.UTF8.GetBytes("0123456789abcdefghijklmnopqrstuvwxyz"));
Console.WriteLine(val);
// ...Printer: ValueByteArray: 30-31-32-33-34-35-36-37-38-39-61-62-63-64-65-66-67-68-69-6A-6B-6C-6D-6E-6F-70-71-72-73-74-75-76-77-78-79-7A - ValueString: 0123456789abcdefghijklmnopqrstuvwxyz

```

6. Thus the only remaining issue is how to deal with overly long strings. This is already an issue in languages with a REPL, eg Python. The python library has a module reprlib which deals with [this specific case](https://docs.python.org/3/library/reprlib.html#reprlib.Repr.maxstring). By default they truncate a string to 30 characters. The default truncation policy is: if a string exceeds 30 characters, return [first 13 characters of the string] + "..." + [last 14 characters of string]". For example

```
In [14]: s = "0123456789abcdefghijklmnopqrstuvwxyz"

In [15]: len(s)
Out[15]: 36

In [16]: r.repr(s)
Out[16]: "'0123456789ab...nopqrstuvwxyz'"
```

We can apply this truncation policy to both strings and the hex representation of the byte array:

```csharp
val = new Printer(Encoding.UTF8.GetBytes("0123456789abcdefghijklmnopqrstuvwxyz"));
Console.WriteLine(val);
// ...Printer: ValueByteArray: 30-31-32-33-3...76-77-78-79-7A - ValueString: 0123456789abc...mnopqrstuvwxyz

**Comment by cprice404** [comment]
@malandis your suggestion looks fine but I would probably truncate to 10 or 20 bytes instead of 30, especially if you are going to print both formats in the output.

I don't feel strongly though so feel free to just make a call.

**Comment by malandis** [comment]
20 sounds good. Also I'm going to put the string representation first and binary second.

**Comment by schwern** [comment]
FWIW I did a similar thing in Ruby, I gave the GetResponse a #to_s method. Ruby will convert what it can to characters, and leave the rest as hex.

```
"\xDE\xAD\xBE\xEF".to_s # "ޭ\xBE\xEF"
```

**Comment by cprice404** [comment]
@Schwern I really think we need to truncate at some length in these to_s functions.  We know we will have users storing objects that are 1-5MB.  It’s possible that we will have users storing objects that are 50mb, 100mb or even larger in the future.

**Comment by schwern** [comment]
I put this in as momentohq/client-sdk-ruby#27.

Something to consider is the debugging use of ToString vs using it as as string. The first might need to be truncated, the second should not be truncated. Ruby has #inspect to split the uses.

**Comment by malandis** [comment]
@schwern that's a great point. C# has this https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute?view=net-7.0
